# Generated by Django 2.2.4 on 2019-08-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.TextField()),
                ('r_seq', models.TextField()),
                ('keys', models.TextField()),
            ],
            options={
                'verbose_name': 'dec_key',
                'verbose_name_plural': 'dec_keys',
                'db_table': 'dec_key',
                'managed': True,
            },
        ),
    ]
