# Generated by Django 2.2.4 on 2019-08-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deckey',
            options={'verbose_name': 'dec_key', 'verbose_name_plural': 'dec_keys'},
        ),
    ]
