# Generated by Django 2.2.4 on 2019-08-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0002_auto_20190819_2041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deckey',
            table='',
        ),
    ]
