# Generated by Django 2.2.4 on 2019-08-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0003_auto_20190819_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deckey',
            options={},
        ),
        migrations.AlterModelTable(
            name='deckey',
            table=None,
        ),
    ]
