# Generated by Django 2.2.4 on 2019-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec', '0004_auto_20190819_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckey',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
