# Generated by Django 2.2.4 on 2019-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.TextField()),
                ('account_number', models.AutoField(primary_key=True, serialize=False)),
                ('odec', models.IntegerField()),
                ('aadhar_number', models.CharField(max_length=50)),
                ('current_balance', models.BigIntegerField()),
            ],
        ),
    ]
