# Generated by Django 2.2.1 on 2019-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enc', '0002_auto_20190820_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='odec',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
