# Generated by Django 2.2.1 on 2019-08-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enc', '0004_auto_20190820_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_balance',
            field=models.TextField(),
        ),
    ]
